from pathlib import Path
import json

ROOT=Path(__file__).parent
NAV=[('index.html','首页'),('menu.html','招牌产品'),('about.html','品牌故事'),('stores.html','门店空间'),('news.html','品牌动态')]
PRODUCTS=[
 ('dry-chili.webp','招牌干海椒抄手','干香辣','干海椒香气直给，拌开就香。','dry spicy'),
 ('green-pepper.webp','藤椒抄手','椒麻鲜','藤椒清香与麻感，入口清爽。','numbing fresh'),
 ('hotpot.webp','火锅抄手','红油香','熟悉的火锅香，包进一碗抄手。','spicy rich'),
 ('sour-spicy.webp','酸辣抄手','酸辣味','酸香先到，辣味随后，开胃利落。','sour spicy'),
 ('tomato-beef.webp','番茄牛腩抄手','浓汤味','番茄酸甜与牛腩炖香，汤感厚实。','soup rich'),
 ('chicken-bamboo.webp','土鸡竹荪抄手','清炖味','土鸡鲜香与竹荪清润，温和耐吃。','soup fresh'),
 ('bamboo-beef.webp','烟笋牛腩抄手','川味炖香','烟笋香气与牛腩浓郁感叠加。','rich spicy'),
 ('mushroom-chicken.webp','姬松茸炖鸡抄手','菌汤味','菌菇香与鸡汤融合，鲜而不重。','soup fresh'),
 ('pickled-fish.webp','酸菜鱼抄手','酸鲜味','酸菜的爽与鱼汤的鲜，层次清晰。','sour fresh'),
 ('classic.webp','传统水饺味抄手','经典味','回到一碗朴实、熟悉的家常味。','classic fresh'),
]

def nav(current):
    links=''.join(f'<a class="{"current" if href==current else ""}" href="{href}">{label}</a>' for href,label in NAV)
    return f'''<header class="site-head"><div class="wrap head-inner"><a class="logo" href="index.html"><img src="../assets/brand-mark.png" alt="八二小区抄手"><span><b>八二小区抄手</b><small>PEPPER WONTON · CHENGDU</small></span></a><nav class="nav" aria-label="主导航">{links}<a class="nav-cta {"current" if current=="partner.html" else ""}" href="partner.html">合作加盟</a></nav><button class="hamburger" type="button" aria-label="打开导航" aria-expanded="false"><i></i><i></i><i></i></button></div></header>'''

def footer():
    return '''<footer class="site-foot"><div class="wrap"><div class="foot-grid"><div class="foot-brand"><img src="../assets/brand-mark.png" alt=""><p>成都建设巷走出来的西南风味抄手。产品第一，味型先行。</p></div><div><h4>探索</h4><a href="menu.html">招牌产品</a><a href="about.html">品牌故事</a><a href="stores.html">门店空间</a></div><div><h4>了解</h4><a href="news.html">品牌动态</a><a href="partner.html">合作加盟</a><a href="../">项目中心</a></div><div><h4>联系</h4><span>正式联系方式待品牌方确认</span><span>合作有风险，决策需谨慎</span></div></div><div class="foot-bottom"><span>© 2026 八二小区抄手 · 官网设计预览</span><span>内容与图片用于项目评审，正式上线前统一校验</span></div></div></footer>'''

def layout(title,description,current,body,structured=None):
    schema=''
    if structured:
        schema=f'<script type="application/ld+json">{json.dumps(structured,ensure_ascii=False,separators=(",",":"))}</script>'
    return f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{description}"><meta name="theme-color" content="#b54634"><title>{title}</title><link rel="stylesheet" href="styles.css">{schema}</head><body>{nav(current)}<main>{body}</main>{footer()}<script src="app.js"></script></body></html>'''

def product_cards(full=False):
    selected=PRODUCTS if full else PRODUCTS[:6]
    cards=[]
    for i,(img,name,flavor,desc,tags) in enumerate(selected):
        featured=' featured' if i==0 and not full else ''
        cards.append(f'<article class="product-card{featured} reveal" data-flavor="{tags}"><img src="../assets/products/{img}" alt="{name}"><div class="info"><small>{flavor}</small><h3>{name}</h3><p>{desc}</p></div></article>')
    return ''.join(cards)

home=f'''<section class="wrap hero"><div class="hero-copy reveal"><p class="eyebrow">成都建设巷 · 西南风味抄手</p><h1 class="display">先让人想吃，<br>再让人记住。</h1><p class="lead">八二抄手的核心是产品。我们把<strong>干香、椒麻、红油、酸辣、浓汤与炖香</strong>包进一碗抄手，让每一种西南味道都有清晰记忆。</p><div class="hero-actions"><a class="button primary" href="menu.html">看看今天吃什么</a><a class="button light" href="about.html">从建设巷说起</a></div><div class="hero-points"><div><b>产品第一</b><span>真实菜品建立食欲</span></div><div><b>西南味型</b><span>麻辣鲜香不止一种</span></div><div><b>现包现卖</b><span>看得见的门店动作</span></div></div></div><div class="hero-stage reveal"><div class="hero-product"><img src="../assets/products/dry-chili.webp" alt="招牌干海椒抄手"></div><div class="hero-card a"><img src="../assets/products/green-pepper.webp" alt="藤椒抄手"></div><div class="hero-card b"><img src="../assets/products/hotpot.webp" alt="火锅抄手"></div><i class="flavor-seal seal-a">麻</i><i class="flavor-seal seal-b">辣</i></div></section><div class="city-ribbon" aria-hidden="true"></div>
<section class="section"><div class="wrap"><header class="section-head reveal"><div><p class="eyebrow">Signature Flavors</p><h2 class="section-title">一碗抄手，<br>六种西南想象</h2></div><p>不按“菜单编号”认识产品，而是按口味找到想吃的那一碗。每种味型都从真实食材、汤底和浇头出发。</p></header><div class="flavor-tabs reveal"><button class="active" data-filter="all">全部味型</button><button data-filter="spicy">香辣</button><button data-filter="numbing">椒麻</button><button data-filter="sour">酸鲜</button><button data-filter="soup">汤鲜</button></div><div class="product-grid">{product_cards()}</div></div></section>
<section class="section dark-section"><div class="wrap"><header class="section-head reveal"><div><p class="eyebrow">Fresh Made</p><h2 class="section-title">好吃不是口号，<br>是看得见的过程</h2></div><p>官网把产品细节放到品牌故事之前：先展示抄手皮、馅料、汤底和上桌状态，再讲八二从哪里来。</p></header><div class="craft-grid"><figure class="craft-visual reveal"><img src="assets/fresh-made-sign.webp" alt="八二小区抄手现包现卖视觉"><figcaption><span class="eyebrow">Open Kitchen</span><h3>现包现卖，热气上桌</h3><p>用门店明档与真实制作动作，建立新鲜感和信任感。</p></figcaption></figure><div class="craft-list"><article class="craft-item reveal"><span>01 · WRAPPER</span><b>皮要薄，也要兜得住鲜</b><p>重点呈现抄手皮的轻薄、煮后状态与入口口感。</p></article><article class="craft-item reveal"><span>02 · FILLING</span><b>馅要鲜，味道才立得住</b><p>产品摄影保留肉馅、葱花、椒粒和真实汁水，不做塑料感修图。</p></article><article class="craft-item reveal"><span>03 · SOUP &amp; TOPPING</span><b>汤底和浇头，决定第二口</b><p>红油、藤椒、酸菜、牛腩与菌汤各自建立清晰风味证据。</p></article></div></div></div></section>
<section class="section"><div class="wrap story-grid"><figure class="story-art reveal"><img src="assets/appetite-illustration.webp" alt="八二小区抄手品牌人物与大碗抄手插画"></figure><div class="story-copy reveal"><p class="eyebrow">Born in Chengdu</p><blockquote>建设巷的烟火气，<br>包进一碗抄手里。</blockquote><p>品牌故事不做遥远的宏大叙事，而是从成都社区日常出发：一碗热食、熟悉的麻辣鲜香，以及邻里间直接、热情的表达。</p><div class="story-stats"><div><b>成都</b><span>地域味觉出处</span></div><div><b>社区</b><span>亲切品牌关系</span></div><div><b>抄手</b><span>产品核心记忆</span></div></div></div></div></section>
<section class="section"><div class="wrap store-band reveal"><div class="photo" role="img" aria-label="成都城市与门店空间视觉"></div><div class="copy"><p class="eyebrow" style="color:var(--gold)">Store Experience</p><h2>明档、热气、<br>一眼看见好吃</h2><p>门店空间延续砖红与暖白，让产品、制作动作和品牌人物成为视觉焦点；省内外店招保留清晰的地域识别。</p><a class="button" href="stores.html">查看门店语言</a></div></div></section>
<section class="section"><div class="wrap"><header class="section-head reveal"><div><p class="eyebrow">Brand Journal</p><h2 class="section-title">把新品、新店与<br>成都味道持续写下来</h2></div><p>正式上线后，品牌动态将承接产品知识、门店故事与城市内容，形成可持续的 SEO 内容资产。</p></header><div class="news-grid"><article class="news-card reveal"><time>内容计划 · 产品知识</time><h3>西南味型，不只是“辣”</h3><p>从藤椒、干海椒、酸菜、牛腩与菌汤说清楚不同口味的入口体验。</p><a href="news.html">查看内容中心 →</a></article><article class="news-card reveal"><time>内容计划 · 门店</time><h3>一间让人看见现包过程的门店</h3><p>讲明档、动线与上桌热气如何构成品牌体验。</p><a href="stores.html">查看门店空间 →</a></article><article class="news-card reveal"><time>内容计划 · 品牌</time><h3>从建设巷到更多城市</h3><p>保留成都出处，同时建立全国消费者都能理解的产品表达。</p><a href="about.html">阅读品牌故事 →</a></article></div></div></section>
<section class="join-strip"><div class="wrap join-inner"><div><h2>想把这碗西南味道，<br>带到更多城市？</h2><p>了解合作条件、支持体系与标准流程。合作有风险，决策需谨慎。</p></div><a class="button" href="partner.html">查看合作信息</a></div></section>'''

menu=f'''<section class="wrap page-hero reveal"><p class="eyebrow">Signature Menu</p><h1 class="display">按味型，<br>找到想吃的那一碗</h1><p class="lead">从干香椒麻到浓汤炖香，10 款产品不是一张拥挤菜单，而是一张清晰的西南风味地图。</p><nav class="page-nav"><a href="#all">全部产品</a><a href="#spicy">香辣椒麻</a><a href="#soup">浓汤炖香</a></nav></section><section class="content-block" id="all"><div class="wrap"><div class="flavor-tabs"><button class="active" data-filter="all">全部</button><button data-filter="spicy">香辣</button><button data-filter="numbing">椒麻</button><button data-filter="sour">酸鲜</button><button data-filter="soup">汤鲜</button><button data-filter="classic">经典</button></div><div class="product-grid menu-full">{product_cards(True)}</div></div></section><section class="content-block dark-section"><div class="wrap"><header class="section-head"><div><p class="eyebrow">Product Language</p><h2 class="section-title">每款产品都要回答：<br>闻起来什么香？入口什么感觉？</h2></div><p>正式文案将基于配方与试吃事实补充，不使用“最好”“第一”“顶级”等绝对化词汇。</p></header></div></section>'''

about='''<section class="wrap page-hero reveal"><p class="eyebrow">Our Story</p><h1 class="display">从建设巷出发，<br>把成都味道包进日常</h1><p class="lead">八二小区抄手的品牌感，不来自做旧滤镜，而来自真实的社区关系、直爽表达与一碗热腾腾的产品。</p></section><section class="content-block"><div class="wrap story-grid"><figure class="story-art reveal"><img src="assets/appetite-illustration.webp" alt="八二小区抄手品牌插画"></figure><div class="story-copy reveal"><p class="eyebrow">Brand Character</p><blockquote>热情、直接、<br>有味道，也有分寸。</blockquote><p>品牌人物是亲切的社区主理人形象；在官网中作为导览与情绪符号出现，不替代真实产品和门店内容。</p><div class="story-stats"><div><b>烟火</b><span>不是喧闹堆砌</span></div><div><b>亲切</b><span>不是廉价促销</span></div><div><b>现代</b><span>不是抹掉成都感</span></div></div></div></div></section><section class="content-block"><div class="wrap"><header class="section-head"><div><p class="eyebrow">Values</p><h2 class="section-title">品牌表达的三个原则</h2></div></header><div class="values"><article class="value"><span class="eyebrow">01</span><h3>产品说真话</h3><p>用真实菜品、真实口感和真实制作动作建立食欲，不靠空泛“匠心”。</p></article><article class="value"><span class="eyebrow">02</span><h3>地域有出处</h3><p>成都与建设巷是味觉和性格来源，而不是表面贴一层城市符号。</p></article><article class="value"><span class="eyebrow">03</span><h3>扩张有秩序</h3><p>不同城市保持同一品牌骨架，同时允许店招与内容保留地域版本。</p></article></div></div></section><section class="content-block dark-section"><div class="wrap"><header class="section-head"><div><p class="eyebrow">Visual Language</p><h2 class="section-title">砖红、暖白、麦金，<br>让热气和产品成为焦点</h2></div><p>官网不使用大面积高饱和红底轰炸，也不做杂乱复古拼贴；通过清晰网格和充足留白保持现代餐饮品牌秩序。</p></header></div></section>'''

stores='''<section class="wrap page-hero reveal"><p class="eyebrow">Store Experience</p><h1 class="display">一眼看见现包，<br>一进门就知道吃什么</h1><p class="lead">门店设计服务于产品决策：清晰门头、明档动作、味型菜单与热气上桌共同构成体验。</p></section><section class="content-block"><div class="wrap space-grid"><article class="space-card reveal"><img src="assets/fresh-made-sign.webp" alt="现包现卖门店视觉"><div class="caption"><h3>明档现包</h3><p>把制作动作放到消费者视线中，形成“正在发生”的新鲜感。</p></div></article><article class="space-card reveal"><img src="assets/chengdu-wall.webp" alt="成都城市墙画视觉"><div class="caption"><h3>成都出处</h3><p>城市图形控制在辅助层级，给产品和人留下呼吸空间。</p></div></article></div></section><section class="content-block"><div class="wrap"><header class="section-head"><div><p class="eyebrow">Store Rules</p><h2 class="section-title">从门头到上桌，<br>保持同一种品牌感觉</h2></div></header><div class="values"><article class="value"><span class="eyebrow">01 · SIGN</span><h3>门头先读品牌</h3><p>主品牌名称清晰完整，地域版本作为辅助，不挤压识别。</p></article><article class="value"><span class="eyebrow">02 · OPEN KITCHEN</span><h3>动作比装饰重要</h3><p>现包、下锅、出餐的真实动作，是门店最有说服力的内容。</p></article><article class="value"><span class="eyebrow">03 · MENU</span><h3>按味型降低选择成本</h3><p>香辣、椒麻、酸鲜、浓汤等标签帮助消费者快速做决定。</p></article></div></div></section>'''

news='''<section class="wrap page-hero reveal"><p class="eyebrow">Brand Journal</p><h1 class="display">产品、新店与<br>成都味道的持续记录</h1><p class="lead">内容中心将保留旧官网历史文章，并持续产出有真实品牌信息与产品经验的新内容。</p></section><section class="content-block"><div class="wrap"><header class="section-head"><div><p class="eyebrow">Migration & New Content</p><h2 class="section-title">历史内容不断档，<br>新内容不为堆关键词</h2></div><p>旧站文章按原 URL、日期、正文和媒体建立迁移映射；新内容先审核事实与合规，再进入发布。</p></header><div class="article-list"><article class="article-row"><time>内容规划</time><h3>西南味型，不只是“辣”</h3><span>产品知识 →</span></article><article class="article-row"><time>内容规划</time><h3>现包抄手的皮、馅与汤底如何影响口感</h3><span>制作过程 →</span></article><article class="article-row"><time>历史迁移</time><h3>旧官网 266 条新闻与视频内容正在建立完整映射</h3><span>迁移中 →</span></article></div></div></section><section class="content-block dark-section"><div class="wrap"><header class="section-head"><div><p class="eyebrow">Editorial Rule</p><h2 class="section-title">每篇内容都要有<br>品牌独有的信息增量</h2></div><p>真实产品、门店案例、原创图片和品牌观点优先；不生成低价值批量页面，不承诺排名结果。</p></header></div></section>'''

partner='''<section class="wrap page-hero reveal"><p class="eyebrow">Partnership</p><h1 class="display">合作信息清楚一点，<br>决策就踏实一点</h1><p class="lead">本页只呈现合作条件、支持内容、标准流程和风险提示。具体费用、区域与资格以正式审核和书面文件为准。</p></section><section class="content-block"><div class="wrap"><header class="section-head"><div><p class="eyebrow">Support System</p><h2 class="section-title">从筹备到运营，<br>每一步说明白</h2></div></header><div class="partner-grid"><article class="partner-card"><span class="eyebrow">Brand</span><h3>品牌与空间规范</h3><p>提供店招、空间、菜单与品牌物料的统一标准，正式版本以合同附件为准。</p></article><article class="partner-card"><span class="eyebrow">Product</span><h3>产品与操作标准</h3><p>围绕核心产品、制作流程与出品一致性建立培训和检查机制。</p></article><article class="partner-card"><span class="eyebrow">Opening</span><h3>筹备与开业协同</h3><p>按项目节点推进选址评估、设计、培训、物料和开业准备。</p></article><article class="partner-card"><span class="eyebrow">Operation</span><h3>运营支持信息</h3><p>具体支持范围、频次和条件以正式合作协议及实际执行计划为准。</p></article></div></div></section><section class="content-block"><div class="wrap"><header class="section-head"><div><p class="eyebrow">Standard Process</p><h2 class="section-title">合作流程</h2></div></header><div class="flow"><article><h3>了解品牌</h3><p>阅读产品、品牌与合作信息。</p></article><article><h3>提交意向</h3><p>提供城市、资源和项目基本情况。</p></article><article><h3>双方评估</h3><p>对资格、区域与项目条件进行核验。</p></article><article><h3>书面确认</h3><p>以正式合同和附件明确权利义务。</p></article></div><div class="risk"><strong>风险提示：</strong>合作经营受选址、市场、管理、成本等多重因素影响，不承诺收益、回本周期或经营结果。请充分评估并审慎决策。</div></div></section>'''

schema={'@context':'https://schema.org','@type':'Restaurant','name':'八二小区抄手','servesCuisine':['川味','抄手','西南风味'],'description':'成都建设巷走出来的西南风味抄手品牌。'}
pages={
 'index.html':layout('八二小区抄手｜成都建设巷的西南风味抄手','八二小区抄手，以真实产品和西南特色口味为核心，呈现招牌抄手、现包过程、品牌故事与门店体验。','index.html',home,schema),
 'menu.html':layout('招牌产品｜八二小区抄手','查看八二小区抄手的招牌干海椒、藤椒、火锅、酸辣、牛腩与菌汤等西南味型产品。','menu.html',menu),
 'about.html':layout('品牌故事｜八二小区抄手','了解八二小区抄手从成都建设巷出发的品牌故事与视觉语言。','about.html',about),
 'stores.html':layout('门店空间｜八二小区抄手','了解八二小区抄手的门头、明档现包、菜单与成都地域空间表达。','stores.html',stores),
 'news.html':layout('品牌动态｜八二小区抄手','八二小区抄手产品知识、门店故事、品牌动态与历史内容迁移。','news.html',news),
 'partner.html':layout('合作加盟｜八二小区抄手','了解八二小区抄手合作条件、支持体系、标准流程与风险提示。','partner.html',partner),
}
for name,content in pages.items(): (ROOT/name).write_text(content)
print('generated',len(pages),'pages')
